-- ============================================================
-- ENTERPRISE BANK FRAUD ANALYTICS
-- DATABASE AND SCHEMA SETUP
-- ============================================================

CREATE DATABASE IF NOT EXISTS BANK_FRAUD_DB;

USE DATABASE BANK_FRAUD_DB;

CREATE SCHEMA IF NOT EXISTS RAW;

CREATE SCHEMA IF NOT EXISTS STAGING;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE SCHEMA IF NOT EXISTS ML;

CREATE WAREHOUSE IF NOT EXISTS BANK_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE BANK_WH;

SHOW DATABASES LIKE 'BANK_FRAUD_DB';

SHOW SCHEMAS;

SHOW WAREHOUSES;