-- ============================================
-- ENTERPRISE BANK FRAUD ANALYTICS
-- DATA VALIDATION QUERIES
-- ============================================

USE DATABASE BANK_FRAUD_DB;
USE WAREHOUSE BANK_WH;

-- 1. Check total transaction count
SELECT COUNT(*) AS TOTAL_TRANSACTIONS
FROM ANALYTICS.VW_POWERBI_DATA;


-- 2. Check fraud transaction count
SELECT
    COUNT(*) AS FRAUD_TRANSACTIONS
FROM ANALYTICS.VW_POWERBI_DATA
WHERE FRAUD_BOOL = 1;


-- 3. Check legitimate transaction count
SELECT
    COUNT(*) AS LEGITIMATE_TRANSACTIONS
FROM ANALYTICS.VW_POWERBI_DATA
WHERE FRAUD_BOOL = 0;


-- 4. Check fraud status distribution
SELECT
    FRAUD_BOOL,
    COUNT(*) AS TRANSACTION_COUNT
FROM ANALYTICS.VW_POWERBI_DATA
GROUP BY FRAUD_BOOL
ORDER BY FRAUD_BOOL;


-- 5. Check payment type distribution
SELECT
    PAYMENT_TYPE,
    COUNT(*) AS TRANSACTION_COUNT
FROM ANALYTICS.VW_POWERBI_DATA
GROUP BY PAYMENT_TYPE
ORDER BY TRANSACTION_COUNT DESC;


-- 6. Check device OS distribution
SELECT
    DEVICE_OS,
    COUNT(*) AS TRANSACTION_COUNT
FROM ANALYTICS.VW_POWERBI_DATA
GROUP BY DEVICE_OS
ORDER BY TRANSACTION_COUNT DESC;


-- 7. Check employment status distribution
SELECT
    EMPLOYMENT_STATUS,
    COUNT(*) AS TRANSACTION_COUNT
FROM ANALYTICS.VW_POWERBI_DATA
GROUP BY EMPLOYMENT_STATUS
ORDER BY TRANSACTION_COUNT DESC;


-- 8. Check housing status distribution
SELECT
    HOUSING_STATUS,
    COUNT(*) AS TRANSACTION_COUNT
FROM ANALYTICS.VW_POWERBI_DATA
GROUP BY HOUSING_STATUS
ORDER BY TRANSACTION_COUNT DESC;


-- 9. Check foreign request distribution
SELECT
    FOREIGN_REQUEST,
    COUNT(*) AS REQUEST_COUNT
FROM ANALYTICS.VW_POWERBI_DATA
GROUP BY FOREIGN_REQUEST
ORDER BY FOREIGN_REQUEST;


-- 10. Check null values in important fields
SELECT
    COUNT_IF(FRAUD_BOOL IS NULL) AS NULL_FRAUD_BOOL,
    COUNT_IF(PAYMENT_TYPE IS NULL) AS NULL_PAYMENT_TYPE,
    COUNT_IF(DEVICE_OS IS NULL) AS NULL_DEVICE_OS,
    COUNT_IF(CUSTOMER_AGE IS NULL) AS NULL_CUSTOMER_AGE,
    COUNT_IF(INCOME IS NULL) AS NULL_INCOME,
    COUNT_IF(CREDIT_RISK_SCORE IS NULL) AS NULL_CREDIT_RISK_SCORE
FROM ANALYTICS.VW_POWERBI_DATA;