-- ============================================
-- ENTERPRISE BANK FRAUD ANALYTICS
-- TEST QUERIES
-- ============================================

USE DATABASE BANK_FRAUD_DB;
USE WAREHOUSE BANK_WH;


-- 1. Test Power BI view
SELECT *
FROM ANALYTICS.VW_POWERBI_DATA
LIMIT 10;


-- 2. Test fraud overview
SELECT *
FROM ANALYTICS.VW_FRAUD_OVERVIEW
LIMIT 10;


-- 3. Test monthly fraud analysis
SELECT *
FROM ANALYTICS.VW_MONTHLY_FRAUD
LIMIT 10;


-- 4. Test payment analysis
SELECT *
FROM ANALYTICS.VW_PAYMENT_ANALYSIS
LIMIT 10;


-- 5. Test customer analysis
SELECT *
FROM ANALYTICS.VW_CUSTOMER_ANALYSIS
LIMIT 10;


-- 6. Test device analysis
SELECT *
FROM ANALYTICS.VW_DEVICE_ANALYSIS
LIMIT 10;


-- 7. Fraud rate test
SELECT
    COUNT(*) AS TOTAL_TRANSACTIONS,
    SUM(FRAUD_BOOL) AS FRAUD_TRANSACTIONS,
    COUNT(*) - SUM(FRAUD_BOOL) AS LEGITIMATE_TRANSACTIONS,
    ROUND(
        SUM(FRAUD_BOOL) * 100.0 / NULLIF(COUNT(*), 0),
        2
    ) AS FRAUD_RATE_PERCENT
FROM ANALYTICS.VW_POWERBI_DATA;


-- 8. Risk category test
SELECT
    RISK_CATEGORY,
    COUNT(*) AS TRANSACTION_COUNT
FROM ANALYTICS.VW_POWERBI_DATA
GROUP BY RISK_CATEGORY
ORDER BY TRANSACTION_COUNT DESC;


-- 9. Payment type fraud test
SELECT
    PAYMENT_TYPE,
    SUM(FRAUD_BOOL) AS FRAUD_TRANSACTIONS
FROM ANALYTICS.VW_POWERBI_DATA
GROUP BY PAYMENT_TYPE
ORDER BY FRAUD_TRANSACTIONS DESC;


-- 10. Device OS fraud test
SELECT
    DEVICE_OS,
    SUM(FRAUD_BOOL) AS FRAUD_TRANSACTIONS
FROM ANALYTICS.VW_POWERBI_DATA
GROUP BY DEVICE_OS
ORDER BY FRAUD_TRANSACTIONS DESC;